//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reser_id { get; set; }
        public System.DateTime reser_date { get; set; }
        public int user_fk_id { get; set; }
        public int product_fk_id { get; set; }
    
        public virtual product product { get; set; }
        public virtual userr userr { get; set; }
    }
}
